config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end 
  resources :griffin_ccs
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  get 'top-secret', to: 'griffin_ccs#index'

  resources :blogs do
  	member do
  		get :toggle_status
	  end
  end

  root to: 'pages#home'
end

app/models/griffin_cc.rb
class GriffinCc < ApplicationRecord
end

app/controllers/griffin_ccs_controller.rb
class GriffinCcsController < ApplicationController
  before_action :set_griffin_cc, only: [:show, :edit, :update, :destroy]
  access all: [:index, :show, :new, :edit, :create, :update, :destroy], user: :all

  # GET /griffin_ccs
  def index
    @griffin_ccs = GriffinCc.all
  end

  # GET /griffin_ccs/1
  def show
  end

  # GET /griffin_ccs/new
  def new
    @griffin_cc = GriffinCc.new
  end

  # GET /griffin_ccs/1/edit
  def edit
  end

  # POST /griffin_ccs
  def create
    @griffin_cc = GriffinCc.new(griffin_cc_params)

    if @griffin_cc.save
      redirect_to @griffin_cc, notice: 'Griffin cc was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /griffin_ccs/1
  def update
    if @griffin_cc.update(griffin_cc_params)
      redirect_to @griffin_cc, notice: 'Griffin cc was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /griffin_ccs/1
  def destroy
    @griffin_cc.destroy
    redirect_to griffin_ccs_url, notice: 'Griffin cc was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_griffin_cc
      @griffin_cc = GriffinCc.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def griffin_cc_params
      params.require(:griffin_cc).permit(:title, :body)
    end
end

app/helpers/griffin_ccs_helper.rb
module GriffinCcsHelper
end

app/views/griffin_ccs/_form.html.erb
<%= form_with(model: griffin_cc, local: true) do |form| %>
  <% if griffin_cc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(griffin_cc.errors.count, "error") %> prohibited this griffin_cc from being saved:</h2>

      <ul>
        <% griffin_cc.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/griffin_ccs/edit.html.erb
<h1>Editing Griffin Cc</h1>

<%= render 'form', griffin_cc: @griffin_cc %>

<%= link_to 'Show', @griffin_cc %> |
<%= link_to 'Back', griffin_ccs_path %>

app/views/griffin_ccs/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Griffin Ccs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @griffin_ccs.each do |griffin_cc| %>
      <tr>
        <td><%= griffin_cc.title %></td>
        <td><%= griffin_cc.body %></td>
        <td><%= link_to 'Show', griffin_cc %></td>
        <td><%= link_to 'Edit', edit_griffin_cc_path(griffin_cc) %></td>
        <td><%= link_to 'Destroy', griffin_cc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Griffin Cc', new_griffin_cc_path %> -->

  <div class="inner cover">
    <h1 class="cover-heading">Griffin's CC</h1>
    <p class="lead">Login for solutions</p>
    <p class="lead">
      <%= link_to 'New Griffin Cc', new_griffin_cc_path, class: "btn btn-lg btn-secondary" %>
    </p>
  </div>

app/views/griffin_ccs/new.html.erb
<h1>New Griffin Cc</h1>

<%= render 'form', griffin_cc: @griffin_cc %>

<%= link_to 'Back', griffin_ccs_path %>

app/views/griffin_ccs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @griffin_cc.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @griffin_cc.body %>
</p>

<%= link_to 'Edit', edit_griffin_cc_path(@griffin_cc) %> |
<%= link_to 'Back', griffin_ccs_path %>